version: "3.4"
services:
  dev-jaeger:
    image: jaegertracing/all-in-one:1.29.0
    container_name: dev-jaeger
    expose:
      - 9411
      - 16686
    ports:
      - 9411:9411
      - 16686:16686
    # Configure it so we can collect data in the zipkin format
    environment:
      COLLECTOR_ZIPKIN_HTTP_PORT: 9411
    # TODO: Add healthcheck for jaeger at some point
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "3"